#!/bin/sh

# upload the firmware to the FX2 EzUSB processor on the ADF435x eval board
# the FW announces itself with VID = 0x04b4 / PID = 0x8613,
# so that the board can be detected by the cyusb program,
# that is used to program an iic file into the large EEPROM

FW_IHX=fx2fakefw.ihx

if [ -r $FW_IHX ]; then
    FIRMWARE=$FW_IHX
else
    echo $(basename $0): error - firmware $FW_IHX not found
    exit 1
fi

FX2UPLOAD=/usr/bin/fx2upload
CYCFX2PROG=/usr/bin/cycfx2prog

if [ -x $CYCFX2PROG ]; then
    $CYCFX2PROG -id=0456.b40d prg:$FIRMWARE && $CYCFX2PROG -id=0456.b40d run
elif [ -x $FX2UPLOAD ]; then
    $FX2UPLOAD -v $FIRMWARE 0x0456 0xb40d
else
    echo $(basename $0): error - utilities $CYCFX2PROG or $FX2UPLOAD not found
    exit 2
fi
