.PHONY: examples
examples:
	make -C adf4351
	make -C set_100


.PHONY: clean
clean:
	make -C adf4351 clean
	make -C set_100 clean


.PHONY: distclean
clean:
	make -C adf4351 distclean
	make -C set_100 distclean
