.PHONY: examples
examples:
	make -C adf4351-eval
	make -C set_100


.PHONY: clean
clean:
	make -C adf4351-eval clean
	make -C set_100 clean


.PHONY: distclean
distclean:
	make -C adf4351-eval distclean
	make -C set_100 distclean
